// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultipleForeignRelation.Data;

namespace MultipleForeignRelation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MultipleForeignRelation.Data.Entities.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BillingStateId")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryStateId")
                        .HasColumnType("int");

                    b.Property<int?>("ShippingStateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillingStateId");

                    b.HasIndex("PrimaryStateId");

                    b.HasIndex("ShippingStateId");

                    b.ToTable("Provider");
                });

            modelBuilder.Entity("MultipleForeignRelation.Data.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("State");
                });

            modelBuilder.Entity("MultipleForeignRelation.Data.Entities.Provider", b =>
                {
                    b.HasOne("MultipleForeignRelation.Data.Entities.State", "BillingState")
                        .WithMany("ProvidersBilling")
                        .HasForeignKey("BillingStateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MultipleForeignRelation.Data.Entities.State", "PrimaryState")
                        .WithMany("ProvidersPrimary")
                        .HasForeignKey("PrimaryStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MultipleForeignRelation.Data.Entities.State", "ShippingState")
                        .WithMany("ProvidersShipping")
                        .HasForeignKey("ShippingStateId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
